Improve (bloat) screenshot wrapper

diff --git a/scripts/.local/bin/screenshot b/scripts/.local/bin/screenshot
--- a/scripts/.local/bin/screenshot
+++ b/scripts/.local/bin/screenshot
@@ -1,9 +1,20 @@
-#!/usr/bin/env sh
+#!/bin/sh
 
-SCREENSHOT_DIR="$HOME"/Pictures/Screenshots
+check_dependency() {
+    if ! command -v "$1" >/dev/null 2>&1; then
+        printf "\033[1;31mError:\033[0m %s is not found. Aborting.\n" "$1" >&2
+        exit 1
+    fi
+}
 
-if [ ! -d "$SCREENSHOT_DIR" ]; then
-    mkdir -p "$SCREENSHOT_DIR"
+for dep in shotgun hacksaw xclip xdotool dmenu notify-send xdg-user-dir; do
+    check_dependency "$dep"
+done
+
+screenshot_dir="$(xdg-user-dir PICTURES)/Screenshots"
+
+if [ ! -d "$screenshot_dir" ]; then
+    mkdir -p "$screenshot_dir"
 fi
 
 clipboard() {
@@ -11,50 +22,70 @@ clipboard() {
 }
 
 full() {
-    filename="$SCREENSHOT_DIR/$(date "+%-Y-%m-%d-%H%M%S")_$HOSTNAME.png"
-    shotgun -s $filename
-    clipboard < $filename
-    notify-send "Capture" "Fullscreen screenshot taken" -i "$filename"
-    echo "$filename"
+    filename="$screenshot_dir/$(date "+%-Y-%m-%d-%H%M%S")_screenshot.png"
+    shotgun -s "$filename" &&
+        notify-send "Capture" "Fullscreen screenshot taken" -i "$filename"
 }
 
 sel() {
-    filename="$SCREENSHOT_DIR/$(date "+%-Y-%m-%d-%H%M%S")_$HOSTNAME.png"
-    selection=$(hacksaw)
-    shotgun -g $selection $filename
-    clipboard < $filename
-    notify-send "Capture" "Selection screenshot taken" -i "$filename"
-    echo "$filename"
+    filename="$screenshot_dir/$(date "+%-Y-%m-%d-%H%M%S")_screenshot.png"
+    shotgun -g "$(hacksaw)" "$filename" &&
+        notify-send "Capture" "Selection screenshot taken" -i "$filename"
 }
 
 active() {
-    get_active_window=$(xdotool getactivewindow)
-    if [ -z $get_active_window ]; then
-        notify-send "Capture" "No active windows"
-        return
-    fi
-
-    filename="$SCREENSHOT_DIR/$(date "+%-Y-%m-%d-%H%M%S")_$HOSTNAME.png"
-    shotgun -i $get_active_window $filename
-    clipboard < $filename
-    notify-send "Capture" "Active window screenshot taken" -i "$filename"
-    echo "$filename"
+    filename="$screenshot_dir/$(date "+%-Y-%m-%d-%H%M%S")_screenshot.png"
+    shotgun -i "$(xdotool getactivewindow)" "$filename" &&
+        notify-send "Capture" "Active window screenshot taken" -i "$filename"
 }
 
-case "$1" in
-    full)
-        shift
+full_copy() {
+    filename="$(mktemp -u --suffix=.png)"
+    shotgun -s "$filename" &&
+        clipboard < "$filename" &&
+        notify-send "Capture" "Fullscreen screenshot saved in clipboard" -i "$filename" &&
+        rm "$filename"
+}
+
+sel_copy() {
+    filename="$(mktemp -u --suffix=.png)"
+    shotgun -g "$(hacksaw)" "$filename" &&
+        clipboard < "$filename" &&
+        notify-send "Capture" "Selection screenshot saved in clipboard" -i "$filename" &&
+        rm "$filename"
+}
+
+active_copy() {
+    filename="$(mktemp -u --suffix=.png)"
+    shotgun -i "$(xdotool getactivewindow)" "$filename" &&
+        clipboard < "$filename" &&
+        notify-send "Capture" "Active window screenshot saved in clipboard" -i "$filename" &&
+        rm "$filename"
+}
+
+case "$(printf "Full Screenshot\\nSelection Screenshot\\nActive Window Screenshot\\nFull Screenshot (copy)\\nSelection Screenshot (copy)\\nActive Window Screenshot (copy)" | dmenu -i)" in
+    "Full Screenshot")
+        sleep 0.5
         full
         ;;
-    sel)
-        shift
+    "Selection Screenshot")
+        sleep 0.5
         sel
         ;;
-    active)
-        shift
+    "Active Window Screenshot")
+        sleep 0.5
         active
         ;;
-    *)
-        full
+    "Full Screenshot (copy)")
+        sleep 0.5
+        full_copy
+        ;;
+    "Selection Screenshot (copy)")
+        sleep 0.5
+        sel_copy
+        ;;
+    "Active Window Screenshot (copy)")
+        sleep 0.5
+        active_copy
         ;;
 esac
